### ISSUE TITLE
wildcards problem with the samples.tsv

### ISSUE THREAD

**Issue by JihedC** [BleekerLab/snakemake_rnaseq#12]
Hi Marc,

I am trying pipeline with my own data. It worked really nicely with the subsample tomato data.
I have adapted the configuration file to change the reference genome and the annotation. 
I have also adapted the `samples.tsv` file to the path of my fastq files. 

It looks like this:

```
sample	R1	R2
Ach1a	/exports/humgen/jihed/MORC3_E9.5_RNA_Seq/data/Ach1_BH81BLADXX_ATCACG_L001_R1.fastq.gz	
Ach1b	/exports/humgen/jihed/MORC3_E9.5_RNA_Seq/data/Ach1_BH81BLADXX_ATCACG_L002_R1.fastq.gz	
Ach2a	/exports/humgen/jihed/MORC3_E9.5_RNA_Seq/data/Ach2_BH81BLADXX_CGATGT_L001_R1.fastq.gz	
```

It's an old single-end RNA-seq, the "R2" column is an empty tab in my tsv file. I saw that your pipeline is able to check if the data is paired or single end. 

The problem is that when I try a dry run, I get this error message:

```
InputFunctionException in line 135 of /exports/humgen/jihed/MORC3_E9.5_RNA_Seq/snakemake_rnaseq/Snakefile:
KeyError: "None of [Index(['fq1'], dtype='object')] are in the [index]"
Wildcards:
sample=Ach1a
```

I don't understand what the problem is here. It seems that the function except the index to have the same name as the sample? 

If you have any idea, where I should look or what I should modify please let me know.

Thanks! 

Jihed

**Comment by mgalland** [comment]
Hey Jihed. 
This is an easy one. The pipeline should actually check the names of the columns of your `samples.tsv` file. 
In your input, these are called `R1` and `R2` while they should be called `fq1` and `fq2`. Can you try to change it?
Please confirm that it worked (or not) + close the issue then so others can see that this is the problem indeed. 
Cheers
Marc

**Comment by JihedC** [comment]
Shame😱 

It worked indeed 😅
